name: Build Project

on:
  workflow_call: # 允许其他工作流调用此工作流
    inputs:
      project:
        required: true
        type: string
    secrets:
      TEST:
        required: true
      BAILIAN_APP_ID:
        required: true
      BAILIAN_API_KEY:
        required: true
env:
  BAILIAN_APP_ID: ${{ secrets.BAILIAN_APP_ID }}
  BAILIAN_API_KEY: ${{ secrets.BAILIAN_API_KEY }}
  SEMVER_TYPE: patch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ inputs.project }}"
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Display Environment Variables
        run: |
          echo "App ID: $BAILIAN_APP_ID"
          echo "API Key: $BAILIAN_API_KEY"
          echo "Semver Type: $SEMVER_TYPE"

      - name: Print project input
        run: |
          echo "当前位置：$(pwd)"
          ls -la
          echo "Project input value is ${{ inputs.project }}"

      - name: console secrets
        run: |
          echo "当前位置：$(pwd)"
          ls -la
          echo "Project secrets test is ${{ secrets.TEST }}"
