name: CI

on:
  push:
    branches:
      - v3

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      all_changed_projects: ${{ steps.set_output.outputs.changed_projects }}
    strategy:
      matrix:
        project:
          - docusaurus
          - dumi

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Initialize environment variable
        if: ${{ matrix.index == 0 }} # Run only once at the beginning
        run: echo "CHANGED_PROJECTS=" >> $GITHUB_ENV

      - name: Check if publish.yaml has changed
        id: check_project
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "${{ matrix.project }}/publish.yaml"; then
            echo "CHANGED_PROJECTS=${{ matrix.project }} $CHANGED_PROJECTS" >> $GITHUB_ENV
          fi

      - name: Set output for all changed projects
        if: ${{ matrix.index == matrix.project.length - 1 }} # Run only once after all projects have been checked
        id: set_output
        run: |
          if [ -z "$CHANGED_PROJECTS" ]; then
            echo "changed_projects=none" >> $GITHUB_OUTPUT
          else
            echo "changed_projects=$(echo $CHANGED_PROJECTS | xargs)" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check_changes
    runs-on: ubuntu-latest
    steps:
      - name: Check if there are any changed projects
        id: output_changed_projects
        run: |
          changed_projects="${{ needs.check_changes.outputs.all_changed_projects }}"
          echo "Changed projects: '${changed_projects}'"
          if [[ "${changed_projects}" == "none" || -z "${changed_projects//[[:space:]]/}" ]]; then
            echo "No changes to build."
            exit 0
          fi

      - name: Call Build Workflow
        run: echo "Calling build workflow for ${{ needs.check_changes.outputs.all_changed_projects }}"
