name: CI

on:
  push:
    branches:
      - v3
    paths:
      - "**/publish.yaml"

jobs:
  find-directories:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.get-directories.outputs.directories }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find modified directories
        id: get-directories
        run: |
            # 获取修改过的文件列表
          MODIFIED_PATHS=$(git diff --name-only HEAD^ HEAD)

          # 初始化一个数组来保存找到的目录
          DIRECTORIES=()

          # 搜索匹配条件的路径并保存目录名称
          for path in $MODIFIED_PATHS; do
            if [[ $path == */publish.yaml ]]; then
              # 提取目录名称并添加到数组
              DIRECTORY=$(dirname "$path")
              DIRECTORIES+=("$DIRECTORY")
            fi
          done

          # 将数组转换为字符串，用逗号分隔
          # DIRECTORIES_STR=$(IFS=,; echo "${DIRECTORIES[*]}")
          echo "Found directories $DIRECTORIES"

          # 导出找到的目录，以便在后续的任务中使用
          echo "directories=$DIRECTORIES_STR" >> $GITHUB_OUTPUT

  print-directories:
    runs-on: ubuntu-latest
    needs: find-directories
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-directories.outputs.directories) }}
    steps:
      - name: Trigger build for each directory
        uses: ./.github/workflows/build-project.yml
        with:
          project: ${{ matrix.dir }}
