name: CI

on:
  push:
    branches:
      - v3

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      all_changed_projects: ${{ steps.expose_changes.outputs.changed_projects }}
    strategy:
      matrix:
        project:
          - docusaurus
          - dumi

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Initialize environment variable
        run: echo "CHANGED_PROJECTS=" >> $GITHUB_ENV

      - name: Check if publish.yaml has changed
        id: check_project
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "${{ matrix.project }}/publish.yaml"; then
            echo "CHANGED_PROJECTS=${{ matrix.project }} $CHANGED_PROJECTS" >> $GITHUB_ENV
          fi

      - name: Expose Changed Projects to Next Step
        id: expose_changes
        run: echo "changed_projects=$CHANGED_PROJECTS" >> $GITHUB_OUTPUT

  collect_all_changes:
    needs: check_changes
    runs-on: ubuntu-latest
    steps:
      - name: Collect changes
        id: collect_all_changes
        run: |
          echo "Changed all_changed_projects: ${{ needs.check_changes.outputs.all_changed_projects }}"
          changed_projects_list=""
          for result in ${{ join(needs.check_changes.outputs.all_changed_projects, ' ') }}; do
            if [[ "$result" != "none" ]]; then
              changed_projects_list="${changed_projects_list} $result"
            fi
          done
          changed_projects_list=$(echo $changed_projects_list | xargs)
          if [[ -z "$changed_projects_list" ]]; then
            changed_projects_list="none"
          fi
          echo "changed_projects=${changed_projects_list}" >> $GITHUB_OUTPUT

  build:
    needs: collect_all_changes
    runs-on: ubuntu-latest
    steps:
      - name: Check if there are any changed projects
        id: output_changed_projects
        run: |
          changed_projects="${{ needs.collect_all_changes.outputs.changed_projects }}"
          echo "Changed projects: '${changed_projects}'"
          if [[ "${changed_projects}" == "none" || -z "${changed_projects//[[:space:]]/}" ]]; then
            echo "No changes to build."
            exit 0
          fi

      - name: Call Build Workflow
        run: echo "Calling build workflow for ${{ needs.collect_all_changes.outputs.changed_projects }}"
